version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:${ETCD_PORT:-2379} -listen-client-urls http://0.0.0.0:${ETCD_PORT:-2379} --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_PORT:-9000}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.3
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:${ETCD_PORT:-2379}
      MINIO_ADDRESS: minio:${MINIO_PORT:-9000}
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "${MILVUS_API_PORT:-19530}:19530"
      - "${MILVUS_METRICS_PORT:-9091}:9091"
    depends_on:
      - "etcd"
      - "minio"

  backend:
    container_name: vibe-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env.local  # Pass environment variables from .env.local
    environment:
      # Override port if needed, otherwise defaults to 8000 from Dockerfile CMD
      # Ensure BACKEND_PORT in .env.local matches the exposed port if overriding
      - BACKEND_PORT=${BACKEND_PORT:-8000}
      # Ensure the backend knows where Milvus is running
      - MILVUS_HOST=standalone
      - MILVUS_PORT=${MILVUS_API_PORT:-19530}
      # Add other necessary backend env vars if they are not in .env.local
      # e.g., OPENAI_API_KEY, GOOGLE_SEARCH_API_KEY, etc. if not using env_file
    ports:
      - "${BACKEND_PORT:-8000}:8000" # Map host port to container port 8000
    volumes:
      # Optional: Mount source code for development with hot-reloading
      # Remove this for production builds
      # - ./backend/src:/app/src
      # Map the main volumes dir for potential file access/storage if needed
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes:/app/volumes
    depends_on:
      - standalone # Depends on Milvus being ready
    networks:
      - default

  frontend:
    container_name: vibe-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:80" # Map host port to Nginx container port 80
    depends_on:
      - backend # Ensures backend starts before frontend Nginx (for proxying)
    networks:
      - default

networks:
  default:
    name: milvus 