# Use this file to define the services that make up your application.
# For more information, see: https://docs.docker.com/compose/compose-file/

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:${ETCD_PORT:-2379} -listen-client-urls http://0.0.0.0:${ETCD_PORT:-2379} --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - vibe-network

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_PORT:-9000}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - vibe-network

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.3
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:${ETCD_PORT:-2379}
      MINIO_ADDRESS: minio:${MINIO_PORT:-9000}
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "${MILVUS_API_PORT:-19530}:19530"
      - "${MILVUS_METRICS_PORT:-9091}:9091"
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - vibe-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  backend:
    container_name: vibe-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env.local
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-8000}
      - MILVUS_HOST=standalone
      - MILVUS_PORT=${MILVUS_API_PORT:-19530}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/models:/app/models
      - ./backend/data:/app/data
    depends_on:
      standalone:
         condition: service_healthy
    networks:
      - vibe-network
    # Add extra_hosts for Linux Docker to resolve host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # --- Add GPU Request using deploy key ---
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # Or 'all' to request all GPUs
              capabilities: [gpu, compute, utility]
    # ---------------------------------------
    command: ["uvicorn", "src.api.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    container_name: vibe-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      backend:
        condition: service_started
      standalone:
        condition: service_healthy
    networks:
      - vibe-network

networks:
  vibe-network:
    name: vibe-network 